services:
  # Κατεβάζω το image postgres, με έκδοση 14 ώστε να φτιάξω μια βάση, κάνω expose το port 5432 καθώς σε αυτό το port ακούει, τρέχει η βάση, ορίζω τις μεταβλητές περιβάλλοντος,
  # δηλαδή όνομα χρήστη βάσης, τον κωδικό του και το όνομα της βάσης και τέλος κάνω έναν έλεγχο για να δω αν η βάση τρέχει με την εντολή pg_isready. 
  db: 
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=compensation
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'dslabdb:/var/lib/postgresql/data/'
  # Ορίζω ότι θα πρέπει να γίνει build το αρχείο nonroot.Dockerfile, ότι το backend θα τρέχει στο port 8080 και ότι για να ξεκινήσει το backend θα πρέπει η βάση να είναι 
  # healthy. Ορίζω τις μεταβλητές περιβάλλοντος, δηλαδή το όνομα της βάσης, το όνομα του χρήστη της βάσης και τον κωδικό του και κάνω έναν έλεγχο με την curl για να δω αν η
  # εφαρμογή μου είναι healthy, τρέχει δηλαδή χωρίς πρόβλημα. Για να τρέξει όμως το spring service, θα πρέπει πρώτα να τρέχει η βάση, να δηλαδή και εκείνη healthy.
  spring:
    image: sp
    build:
      context: .
      dockerfile: nonroot.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compensation
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=pass123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://51.120.247.169:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3
  # Καταβάζω τον frontend κώδικα από το github. Ορίζω ότι το backend θα τρέχει στην παρακάτω IP και ότι το frontend θα τρέχει στο port 9000. 
  frontend:
    # image: front
    build:
      context: https://github.com/JBaizanis/front-repo.git
      # dockerfile: node.Dockerfile
    environment:
     - VITE_BACKEND=http://51.120.247.169:8080
    ports:
      - 9000:80
    depends_on:
      spring:
        condition: service_healthy


volumes:
    dslabdb: